---
- hosts: all
  become: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - include: tasks/os.yml
    - include: tasks/db.yml
    - include: tasks/sonarqube.yml
    - include: tasks/service.yml
